
name: 'retail_pulse'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'retail_pulse'


model-paths: ["models"]
# analysis-paths: ["analyses"]
test-paths: ["tests"]
# seed-paths: ["seeds"]
macro-paths: ["macros"]
# snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

vars:
  local_tz: "Asia/Ho_Chi_Minh"
  date_start: "2020-01-01"
  date_days: 4018

models:
  retail_pulse:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: table
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts
