-- Khởi tạo Snowflake cho RetailPulse. Chạy bằng ACCOUNTADMIN qua `make snowflake-init`
-- (xem trước bằng `make snowflake-init-dry`). Viết để chạy lại nhiều lần không lỗi.
-- Mỗi câu lệnh kết thúc bằng dấu chấm phẩy; chỉ dùng chú thích cả dòng.
-- __RSA_PUBLIC_KEY__ được thay bằng public key của user DLT_LOADER.

USE ROLE ACCOUNTADMIN;

-- Giới hạn chi phí
CREATE RESOURCE MONITOR IF NOT EXISTS RETAIL_RM
  WITH CREDIT_QUOTA = 10 FREQUENCY = MONTHLY START_TIMESTAMP = IMMEDIATELY
  TRIGGERS ON 80 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND;

CREATE WAREHOUSE IF NOT EXISTS RETAIL_WH
  WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE RESOURCE_MONITOR = RETAIL_RM;

CREATE DATABASE IF NOT EXISTS RETAIL_PULSE;
CREATE SCHEMA IF NOT EXISTS RETAIL_PULSE.RAW;

-- Roles
CREATE ROLE IF NOT EXISTS LOADER;
CREATE ROLE IF NOT EXISTS TRANSFORMER;
GRANT ROLE LOADER TO ROLE SYSADMIN;
GRANT ROLE TRANSFORMER TO ROLE SYSADMIN;

-- LOADER: dlt ghi vào RAW
GRANT USAGE ON WAREHOUSE RETAIL_WH TO ROLE LOADER;
GRANT USAGE ON DATABASE RETAIL_PULSE TO ROLE LOADER;
GRANT CREATE SCHEMA ON DATABASE RETAIL_PULSE TO ROLE LOADER;
GRANT ALL ON SCHEMA RETAIL_PULSE.RAW TO ROLE LOADER;

-- TRANSFORMER: dbt đọc RAW, ghi các schema khác
GRANT USAGE ON WAREHOUSE RETAIL_WH TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE RETAIL_PULSE TO ROLE TRANSFORMER;
GRANT CREATE SCHEMA ON DATABASE RETAIL_PULSE TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA RETAIL_PULSE.RAW TO ROLE TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_PULSE.RAW TO ROLE TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_PULSE.RAW TO ROLE TRANSFORMER;

-- User cho dlt (xác thực bằng key pair)
CREATE USER IF NOT EXISTS DLT_LOADER
  TYPE = SERVICE
  DEFAULT_ROLE = LOADER
  DEFAULT_WAREHOUSE = RETAIL_WH;
ALTER USER DLT_LOADER SET RSA_PUBLIC_KEY = '__RSA_PUBLIC_KEY__';
GRANT ROLE LOADER TO USER DLT_LOADER;
