-- Khởi tạo Snowflake cho RetailPulse. Chạy bằng ACCOUNTADMIN qua `make snowflake-init`
-- (xem trước bằng `make snowflake-init-dry`). Viết để chạy lại nhiều lần không lỗi.
-- Mỗi câu lệnh kết thúc bằng dấu chấm phẩy; chỉ dùng chú thích cả dòng.
-- __DLT_LOADER_PUBLIC_KEY__, __DBT_TRANSFORMER_PUBLIC_KEY__, __GITHUB_CI_PUBLIC_KEY__ được thay bằng public key của từng user.

USE ROLE ACCOUNTADMIN;

-- Giới hạn chi phí
CREATE RESOURCE MONITOR IF NOT EXISTS RETAIL_RM
  WITH CREDIT_QUOTA = 10 FREQUENCY = MONTHLY START_TIMESTAMP = IMMEDIATELY
  TRIGGERS ON 80 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND;

CREATE WAREHOUSE IF NOT EXISTS RETAIL_WH
  WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE RESOURCE_MONITOR = RETAIL_RM;

CREATE DATABASE IF NOT EXISTS RETAIL_PULSE;
CREATE SCHEMA IF NOT EXISTS RETAIL_PULSE.RAW;

-- Roles
CREATE ROLE IF NOT EXISTS LOADER;
CREATE ROLE IF NOT EXISTS TRANSFORMER;
GRANT ROLE LOADER TO ROLE SYSADMIN;
GRANT ROLE TRANSFORMER TO ROLE SYSADMIN;

-- LOADER: dlt ghi vào RAW
GRANT USAGE ON WAREHOUSE RETAIL_WH TO ROLE LOADER;
GRANT USAGE ON DATABASE RETAIL_PULSE TO ROLE LOADER;
GRANT CREATE SCHEMA ON DATABASE RETAIL_PULSE TO ROLE LOADER;
GRANT ALL ON SCHEMA RETAIL_PULSE.RAW TO ROLE LOADER;

-- TRANSFORMER: dbt đọc RAW, ghi các schema khác
GRANT USAGE ON WAREHOUSE RETAIL_WH TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE RETAIL_PULSE TO ROLE TRANSFORMER;
GRANT CREATE SCHEMA ON DATABASE RETAIL_PULSE TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA RETAIL_PULSE.RAW TO ROLE TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_PULSE.RAW TO ROLE TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_PULSE.RAW TO ROLE TRANSFORMER;

-- User cho dlt (xác thực bằng key pair)
CREATE USER IF NOT EXISTS DLT_LOADER
  TYPE = SERVICE
  DEFAULT_ROLE = LOADER
  DEFAULT_WAREHOUSE = RETAIL_WH;
ALTER USER DLT_LOADER SET RSA_PUBLIC_KEY = '__DLT_LOADER_PUBLIC_KEY__';
GRANT ROLE LOADER TO USER DLT_LOADER;

-- User cho dbt (xác thực bằng key pair riêng, role TRANSFORMER)
CREATE USER IF NOT EXISTS DBT_TRANSFORMER
  TYPE = SERVICE
  DEFAULT_ROLE = TRANSFORMER
  DEFAULT_WAREHOUSE = RETAIL_WH;
ALTER USER DBT_TRANSFORMER SET RSA_PUBLIC_KEY = '__DBT_TRANSFORMER_PUBLIC_KEY__';
GRANT ROLE TRANSFORMER TO USER DBT_TRANSFORMER;

-- Các schema của dbt: TRANSFORMER tạo (làm chủ sở hữu) để dbt ghi được, và để cấp quyền đọc cho CI bên dưới
-- mà không phải đợi lần dbt build đầu tiên.
USE ROLE TRANSFORMER;
CREATE SCHEMA IF NOT EXISTS RETAIL_PULSE.STAGING;
CREATE SCHEMA IF NOT EXISTS RETAIL_PULSE.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS RETAIL_PULSE.MARTS;
USE ROLE ACCOUNTADMIN;

-- CI (GitHub Actions, slim CI cho dbt): chỉ GHI vào database riêng RETAIL_PULSE_CI, chỉ ĐỌC dữ liệu thật.
CREATE RESOURCE MONITOR IF NOT EXISTS RETAIL_CI_RM
  WITH CREDIT_QUOTA = 2 FREQUENCY = MONTHLY START_TIMESTAMP = IMMEDIATELY
  TRIGGERS ON 80 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND;

CREATE WAREHOUSE IF NOT EXISTS RETAIL_CI_WH
  WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE RESOURCE_MONITOR = RETAIL_CI_RM;

CREATE DATABASE IF NOT EXISTS RETAIL_PULSE_CI;

CREATE ROLE IF NOT EXISTS CI_RUNNER;
GRANT ROLE CI_RUNNER TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE RETAIL_CI_WH TO ROLE CI_RUNNER;
GRANT ALL ON DATABASE RETAIL_PULSE_CI TO ROLE CI_RUNNER;

GRANT USAGE ON DATABASE RETAIL_PULSE TO ROLE CI_RUNNER;
GRANT USAGE ON SCHEMA RETAIL_PULSE.RAW TO ROLE CI_RUNNER;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_PULSE.RAW TO ROLE CI_RUNNER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_PULSE.RAW TO ROLE CI_RUNNER;

GRANT USAGE ON SCHEMA RETAIL_PULSE.STAGING TO ROLE CI_RUNNER;
GRANT SELECT ON ALL VIEWS IN SCHEMA RETAIL_PULSE.STAGING TO ROLE CI_RUNNER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA RETAIL_PULSE.STAGING TO ROLE CI_RUNNER;

GRANT USAGE ON SCHEMA RETAIL_PULSE.INTERMEDIATE TO ROLE CI_RUNNER;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_PULSE.INTERMEDIATE TO ROLE CI_RUNNER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_PULSE.INTERMEDIATE TO ROLE CI_RUNNER;

GRANT USAGE ON SCHEMA RETAIL_PULSE.MARTS TO ROLE CI_RUNNER;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_PULSE.MARTS TO ROLE CI_RUNNER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_PULSE.MARTS TO ROLE CI_RUNNER;

CREATE USER IF NOT EXISTS GITHUB_CI
  TYPE = SERVICE
  DEFAULT_ROLE = CI_RUNNER
  DEFAULT_WAREHOUSE = RETAIL_CI_WH;
ALTER USER GITHUB_CI SET RSA_PUBLIC_KEY = '__GITHUB_CI_PUBLIC_KEY__';
GRANT ROLE CI_RUNNER TO USER GITHUB_CI;
