-- Khởi tạo Snowflake cho RetailPulse. Chạy bằng ACCOUNTADMIN qua `make snowflake-init`
-- (xem trước bằng `make snowflake-init-dry`). Viết để chạy lại nhiều lần không lỗi.
--
-- Thứ tự file:
--   1. Chi phí và tính toán   trần credit, warehouse nhỏ tự tắt
--   2. Database và role       nơi chứa dữ liệu, ai được làm gì
--   3. User                   tài khoản của dlt và dbt, đăng nhập bằng key pair
--   4. Schema của dbt         tạo sớm để cấp quyền cho CI
--   5. CI (GitHub Actions)    môi trường riêng cho slim CI, chỉ đọc dữ liệu thật
--
-- Quy ước đọc file: mỗi câu lệnh kết thúc bằng dấu chấm phẩy, chỉ dùng chú thích cả dòng.
-- Các chuỗi __<USER>_PUBLIC_KEY__ được thay bằng public key của từng user lúc chạy.

USE ROLE ACCOUNTADMIN;

-- ===== 1. Chi phí và tính toán =====
-- Resource monitor đặt trần 10 credit mỗi tháng: cảnh báo ở 80 phần trăm, tự dừng ở 100.
-- Warehouse XSMALL tự tắt sau 60 giây không dùng và tự bật khi có truy vấn.
CREATE RESOURCE MONITOR IF NOT EXISTS RETAIL_RM
  WITH CREDIT_QUOTA = 10 FREQUENCY = MONTHLY START_TIMESTAMP = IMMEDIATELY
  TRIGGERS ON 80 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND;

CREATE WAREHOUSE IF NOT EXISTS RETAIL_WH
  WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE RESOURCE_MONITOR = RETAIL_RM;

-- ===== 2. Database và role =====
-- RAW là nơi duy nhất dlt ghi vào. Các schema của dbt được tạo ở mục 4.
CREATE DATABASE IF NOT EXISTS RETAIL_PULSE;
CREATE SCHEMA IF NOT EXISTS RETAIL_PULSE.RAW;

-- LOADER cho dlt, TRANSFORMER cho dbt. Mỗi role chỉ có quyền vừa đủ cho việc của mình.
CREATE ROLE IF NOT EXISTS LOADER;
CREATE ROLE IF NOT EXISTS TRANSFORMER;
GRANT ROLE LOADER TO ROLE SYSADMIN;
GRANT ROLE TRANSFORMER TO ROLE SYSADMIN;

-- LOADER: dlt ghi vào RAW
GRANT USAGE ON WAREHOUSE RETAIL_WH TO ROLE LOADER;
GRANT USAGE ON DATABASE RETAIL_PULSE TO ROLE LOADER;
GRANT CREATE SCHEMA ON DATABASE RETAIL_PULSE TO ROLE LOADER;
GRANT ALL ON SCHEMA RETAIL_PULSE.RAW TO ROLE LOADER;

-- TRANSFORMER: dbt đọc RAW, ghi các schema khác
GRANT USAGE ON WAREHOUSE RETAIL_WH TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE RETAIL_PULSE TO ROLE TRANSFORMER;
GRANT CREATE SCHEMA ON DATABASE RETAIL_PULSE TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA RETAIL_PULSE.RAW TO ROLE TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_PULSE.RAW TO ROLE TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_PULSE.RAW TO ROLE TRANSFORMER;

-- ===== 3. User =====
-- Cả hai user đều đăng nhập bằng key pair (không mật khẩu) và là loại SERVICE.
-- User cho dlt: DLT_LOADER, role LOADER.
CREATE USER IF NOT EXISTS DLT_LOADER
  TYPE = SERVICE
  DEFAULT_ROLE = LOADER
  DEFAULT_WAREHOUSE = RETAIL_WH;
ALTER USER DLT_LOADER SET RSA_PUBLIC_KEY = '__DLT_LOADER_PUBLIC_KEY__';
GRANT ROLE LOADER TO USER DLT_LOADER;

-- User cho dbt: DBT_TRANSFORMER, role TRANSFORMER, key pair riêng.
CREATE USER IF NOT EXISTS DBT_TRANSFORMER
  TYPE = SERVICE
  DEFAULT_ROLE = TRANSFORMER
  DEFAULT_WAREHOUSE = RETAIL_WH;
ALTER USER DBT_TRANSFORMER SET RSA_PUBLIC_KEY = '__DBT_TRANSFORMER_PUBLIC_KEY__';
GRANT ROLE TRANSFORMER TO USER DBT_TRANSFORMER;

-- ===== 4. Schema của dbt =====
-- Phải do role TRANSFORMER tạo để dbt là chủ sở hữu và ghi được bảng vào đó. Tạo sớm để mục 5
-- cấp được quyền đọc cho CI mà không phải đợi lần dbt build đầu tiên.
USE ROLE TRANSFORMER;
CREATE SCHEMA IF NOT EXISTS RETAIL_PULSE.STAGING;
CREATE SCHEMA IF NOT EXISTS RETAIL_PULSE.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS RETAIL_PULSE.MARTS;
USE ROLE ACCOUNTADMIN;

-- ===== 5. CI (GitHub Actions, slim CI cho dbt) =====
-- CI chỉ GHI vào database riêng RETAIL_PULSE_CI và chỉ ĐỌC dữ liệu thật. Warehouse và resource monitor
-- riêng để một workflow chạy sai không đốt credit của pipeline thật.
CREATE RESOURCE MONITOR IF NOT EXISTS RETAIL_CI_RM
  WITH CREDIT_QUOTA = 2 FREQUENCY = MONTHLY START_TIMESTAMP = IMMEDIATELY
  TRIGGERS ON 80 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND;

CREATE WAREHOUSE IF NOT EXISTS RETAIL_CI_WH
  WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE RESOURCE_MONITOR = RETAIL_CI_RM;

CREATE DATABASE IF NOT EXISTS RETAIL_PULSE_CI;

CREATE ROLE IF NOT EXISTS CI_RUNNER;
GRANT ROLE CI_RUNNER TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE RETAIL_CI_WH TO ROLE CI_RUNNER;
GRANT ALL ON DATABASE RETAIL_PULSE_CI TO ROLE CI_RUNNER;

GRANT USAGE ON DATABASE RETAIL_PULSE TO ROLE CI_RUNNER;
GRANT USAGE ON SCHEMA RETAIL_PULSE.RAW TO ROLE CI_RUNNER;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_PULSE.RAW TO ROLE CI_RUNNER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_PULSE.RAW TO ROLE CI_RUNNER;

GRANT USAGE ON SCHEMA RETAIL_PULSE.STAGING TO ROLE CI_RUNNER;
GRANT SELECT ON ALL VIEWS IN SCHEMA RETAIL_PULSE.STAGING TO ROLE CI_RUNNER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA RETAIL_PULSE.STAGING TO ROLE CI_RUNNER;

GRANT USAGE ON SCHEMA RETAIL_PULSE.INTERMEDIATE TO ROLE CI_RUNNER;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_PULSE.INTERMEDIATE TO ROLE CI_RUNNER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_PULSE.INTERMEDIATE TO ROLE CI_RUNNER;

GRANT USAGE ON SCHEMA RETAIL_PULSE.MARTS TO ROLE CI_RUNNER;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_PULSE.MARTS TO ROLE CI_RUNNER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_PULSE.MARTS TO ROLE CI_RUNNER;

CREATE USER IF NOT EXISTS GITHUB_CI
  TYPE = SERVICE
  DEFAULT_ROLE = CI_RUNNER
  DEFAULT_WAREHOUSE = RETAIL_CI_WH;
ALTER USER GITHUB_CI SET RSA_PUBLIC_KEY = '__GITHUB_CI_PUBLIC_KEY__';
GRANT ROLE CI_RUNNER TO USER GITHUB_CI;
